# Generated by Django 5.0.4 on 2024-04-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_option_is_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='is_checkbox',
            new_name='Dogru_cevap',
        ),
    ]
